on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/webdriver-v1.yml'
      - 'v1/**'

name: WebDriver

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        webdriver-test: [ selenium, webdriverio ]
    steps:
      - uses: actions/checkout@v2

      - name: Tauri dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install -y
          libgtk-3-dev
          libgtksourceview-3.0-dev
          webkit2gtk-4.0
          libayatana-appindicator3-dev
          webkit2gtk-driver
          xvfb

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Node v16
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - uses: pnpm/action-setup@v4

      - name: install dependencies
        run: |
          cd v1
          pnpm install
          cd webdriver
          pnpm install

      - name: Install tauri-driver
        run: cargo install tauri-driver --locked

      - name: run tests using WebdriverIO
        run: |
          pnpm install
          xvfb-run pnpm test
        working-directory: v1/webdriver/${{ matrix.webdriver-test }}
